baseURL = "http://clayliddell.com"
title = "Clayton Liddell"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Clayton Liddell"
description = "Clayton Liddell's personal website"
keywords = "blog,developer,personal"
info = "Backend Developer"
avatarURL = "images/avatar.jpg"
#footerContent = "Enter a text here."
dateFormat = "January 2, 2006"
hideNavigationTitle = true
hideFooter = true
hideCredits = false
hideCopyright = false
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/clayliddell/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/clayliddell/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/clayliddell/"

# [[menu.main]]
# name = "About"
# weight = 1
# url = "about/"

# [[menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

# [[menu.main]]
# name = "Projects"
# weight = 3
# url = "projects/"

# [[menu.main]]
# name = "Contact me"
# weight = 5
# url = "contact/"
